### ISSUE TITLE
Retained messages not compatible between MQTTv5 and MQTTv3.1.1

### ISSUE THREAD

**Issue by ckrey** [eclipse/paho.mqtt.testing#51]
Setting:

CONNECT MQTTv3.1.1
PUBLISH with retain flag set
DISCONNECT

CONNECT MQTTv5
SUBSCRIBE

Result:
```
ERROR 20180726 091732 WebSocketTCPHandler
Traceback (most recent call last):
  File "/home/ckrey/paho.mqtt.testing/interoperability/mqtt/brokers/listeners/TCPListeners.py", line 167, in handle
    terminate = broker.handleRequest(sock)
  File "/home/ckrey/paho.mqtt.testing/interoperability/mqtt/brokers/V5/MQTTBrokers.py", line 344, in handleRequest
    terminate = self.handlePacket(packet, sock)
  File "/home/ckrey/paho.mqtt.testing/interoperability/mqtt/brokers/V5/MQTTBrokers.py", line 373, in handlePacket
    getattr(self, MQTTV5.Packets.Names[packet.fh.PacketType].lower())(sock, packet)
  File "/home/ckrey/paho.mqtt.testing/interoperability/mqtt/brokers/V5/MQTTBrokers.py", line 519, in subscribe
    self.broker.subscribe(self.clients[sock].id, topics, optionss)
  File "/home/ckrey/paho.mqtt.testing/interoperability/mqtt/brokers/V5/Brokers.py", line 235, in subscribe
    self.__doRetained__(aClientid, topic, [options for (options, props) in optionsprops], resubscribeds)
  File "/home/ckrey/paho.mqtt.testing/interoperability/mqtt/brokers/V5/Brokers.py", line 227, in __doRetained__
    (ret_msg, ret_qos, properties) = self.se.getRetained(s)
ValueError: not enough values to unpack (expected 3, got 2)
```

Or vice versa when published in MQTTv5 and subscribed from MQTTv3.1.1:
```
ERROR 20180726 091712 WebSocketTCPHandler
Traceback (most recent call last):
  File "/home/ckrey/paho.mqtt.testing/interoperability/mqtt/brokers/listeners/TCPListeners.py", line 167, in handle
    terminate = broker.handleRequest(sock)
  File "/home/ckrey/paho.mqtt.testing/interoperability/mqtt/brokers/V311/MQTTBrokers.py", line 231, in handleRequest
    terminate = self.handlePacket(packet, sock)
  File "/home/ckrey/paho.mqtt.testing/interoperability/mqtt/brokers/V311/MQTTBrokers.py", line 245, in handlePacket
    getattr(self, MQTTV3.packetNames[packet.fh.MessageType].lower())(sock, packet)
  File "/home/ckrey/paho.mqtt.testing/interoperability/mqtt/brokers/V311/MQTTBrokers.py", line 355, in subscribe
    self.broker.subscribe(self.clients[sock].id, topics, qoss)
  File "/home/ckrey/paho.mqtt.testing/interoperability/mqtt/brokers/V311/Brokers.py", line 142, in subscribe
    self.__doRetained__(aClientid, topic, qos)
  File "/home/ckrey/paho.mqtt.testing/interoperability/mqtt/brokers/V311/Brokers.py", line 135, in __doRetained__
    (ret_msg, ret_qos) = self.se.getRetained(s)
ValueError: too many values to unpack (expected 2)
```

**Comment by ckrey** [comment]
probably not tested yet see #44

**Comment by icraggs** [comment]
I've added a fix.

**Comment by ckrey** [comment]
I did a retest and the problem is gone! Thanks
